services:
  db:
    image: uche21/sqlpinacoteca:v1
    container_name: unruffled_davinci
    environment:
      MYSQL_ROOT_PASSWORD: pinacoteca1234
      MYSQL_DATABASE: pinacoteca
      MYSQL_USER: davinci
      MYSQL_PASSWORD: davinci1234
    ports:
      - "3308:3306"
  php:
    image: uche21/pinacoteca:v1
    container_name: phppinacoteca
    ports:
      - "8080:80"
    depends_on:
      - db